### ISSUE TITLE
Plugin API

### ISSUE THREAD

**Issue by ForbesLindesay** [ForbesLindesay/jade-code-gen#20]
I want us to write a plugin API for code-gen, but I currently think it's not quite the right time to do so.  People can always generate arbitrary code anyway by adding unbuffered-code and buffered-code nodes at the parse stage.

**Comment by TimothyGu** [comment]
I feel like there is at least one use case for a plugin API. I was trying to write a plugin that allows users to write ES next code in JavaScript using Babel, but I was unable to do so because the "with" module throws parsing errors on non-ES2015 code.

**Comment by ForbesLindesay** [comment]
I'm happy for us to update `with` to use `babylon`, so we can parse all versions of the code.  I currently really want people to keep treating code-gen as a black box as much as possible, because it gives us the most possible scope for optimisation.

**Comment by jeromew** [comment]
This issue was moved to pugjs/pug#2709
