### ISSUE TITLE
Extra line break pretty if block in mixin contain only text

### ISSUE THREAD

**Issue by werty1001** [ForbesLindesay/jade-code-gen#29]
Hi, extra line break pretty if block in mixin contain only text or inline tags:

``` Pug
mixin test()
    .test&attributes(attributes): block

// Call
+test Test text

```

Output:

``` HTML
<div class="test">Test text
</div>
```

Instead of:

``` HTML
<div class="test">Test text</div>
```

I explored `pug-code-gen/index.js` but dont't found how to fix it.

**Comment by jeromew** [comment]
This issue was moved to pugjs/pug#2707
