### ISSUE TITLE
Code generation performance

### ISSUE THREAD

**Issue by joliss** [ForbesLindesay/jade-code-gen#32]
I was surprised that code generation took such a large percentage of total execution time for Pug, so I took a quick look. Toying around with console.time and the profiler using an [ad-hoc benchmark](https://github.com/joliss/pug-benchmark), it seems that there's a bunch of potential for optimization. Unfortunately I don't have the time right now to take a stab at actually optimizing it, but I wanted to record what I found for posterity.

* The overhead caused by `compileDebug: true` (the default) is about 40% of total ([source](https://github.com/pugjs/pug-code-gen/blob/1107c8c19d75285af63d7f4e94831efe01626493/index.js#L264-L270)). Maybe that's optimizable, or maybe there are cases where we know that we won't need the debug information.
* Much of the code generation time seems to be spent on `this.buf.push`. [This jsPerf](https://jsperf.com/join-concat/2) suggests that it may be quicker to use `+=` to produce a giant string. Maybe there are even more possible optimizations along this line.
* In development mode, or when generating static pages: We may want to disable the Constantinople optimization. Constantinople takes up about 20% of the total time ([source](https://github.com/pugjs/pug-code-gen/blob/1107c8c19d75285af63d7f4e94831efe01626493/index.js#L207-L209)), with `compileDebug: false`.
* In development mode for server-side templates, or when generating static pages: It might be quicker to avoid code generation altogether and produce the output straight from the AST (or some intermediate representation).
* When you have a bunch of interdependent files (via `include` or `extends`) and you're rebuilding them repeatedly in development mode, we might be able to pre-generate some code for each individual file and [cache](https://github.com/pugjs/pug/issues/2668) it, so that we can do less work in the final pass that combines all the files.

**Comment by ForbesLindesay** [comment]
Disabling constantinople is something we could offer as an option.  Unfortunately it's hard to automatically know when people are going to need it.  Perhaps we could disable constantinople by default when people are using `render`/`renderFile` with no `cache` enabled.

There may well be options for optimising compileDebug.  Most notably, https://github.com/pugjs/pug-code-gen/blob/1107c8c19d75285af63d7f4e94831efe01626493/index.js#L264-L270 is the bit I would expect to be costing us a lot of time.  Perhaps we could cache the `stringify`ed filenames.  Perhaps we could avoid outputting that debug information for nodes that we **know** won't throw errors.  For example, if we keep using constaninople, then we can skip outputting debugging info for tags where all attributes are constant (or perhaps just where there are no attributes).

Another approach we could take, is to attempt rendering with `compileDebug: false` then re-compile and re-render if there are any errors.  That would make us 40% (based on your measurements) faster in the case of a successful render, but quite a lot slower in the case of errors.

**Comment by joliss** [comment]
> Disabling constantinople is something we could offer as an option. Unfortunately it's hard to automatically know when people are going to need it.

I think just adding an option would be a big win. It seems to me that there are so many disparate use cases for Pug -- {server-side static, server-side dynamic, client-side dynamic} x {production, development, testing} -- that it's best to just expose all the options and let the tooling that calls Pug determine what combination is best. For example, if a tool like Ember CLI were to use Pug, that kind of tool will generally "know" which set of options is appropriate and call Pug accordingly.

**Comment by jeromew** [comment]
This issue was moved to pugjs/pug#2705
